app = "otomatis"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_PORT = "5678"
  GENERIC_TIMEZONE = "Asia/Jakarta"
  N8N_HOST = "otomatis.fly.dev"
  WEBHOOK_URL = "https://otomatis.fly.dev/"
  TINI_SUBREAPER = "true"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = "true"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[vm]]
  size = "shared-cpu-1x"
  memory = 1g

[checks]
  [checks.web]
    type = "http"
    interval = "10s"
    timeout = "5s"
    path = "/"
    method = "GET"
    grace_period = "30s"
