app = "otomatis"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_PORT = "5678"
  GENERIC_TIMEZONE = "Asia/Jakarta"
  N8N_HOST = "otomatis.fly.dev"
  WEBHOOK_URL = "https://otomatis.fly.dev/"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[vm]]
  size = "shared-cpu-1x"
  memory = 256
